# See: https://www.mkdocs.org/user-guide/configuration/

# Site configuration:
site_name: Conreality Software Development Kit (SDK)
site_author: Conreality Ltd
site_url: https://sdk.conreality.dev
repo_url: https://github.com/conreality/sdk.conreality.dev
google_analytics:

# Content configuration:
remote_name: github
docs_dir: content
site_dir: public
use_directory_urls: false

# Theme configuration:
theme: material

# Table of contents (TOC):
nav:
  - Introduction: index.md
